// Test Case 1: Balanced Positive Emotions and AI Insights for Weeks 1-3

localStorage.setItem("user-emotion-start-date", "2025-09-15");

localStorage.setItem("emotion-logs", JSON.stringify([
  {"id": "1757937600000", "date": "Mon Sep 15 2025", "timestamp": 1757937600000, "mood": 4, "energy": 70, "overwhelm": 30, "emotions": ["excited", "motivated"], "sleepHours": 7.0, "activities": ["worked_personal_goal"], "week": 1},
  {"id": "1758024000000", "date": "Tue Sep 16 2025", "timestamp": 1758024000000, "mood": 3, "energy": 60, "overwhelm": 40, "emotions": ["average", "nervous"], "sleepHours": 6.0, "activities": ["worked_personal_goal"], "week": 1},
  {"id": "1758110400000", "date": "Wed Sep 17 2025", "timestamp": 1758110400000, "mood": 5, "energy": 80, "overwhelm": 20, "emotions": ["joyful", "grateful"], "sleepHours": 8.0, "activities": ["quality_time_kids", "connected_friends_family"], "week": 1},
  {"id": "1758196800000", "date": "Thu Sep 18 2025", "timestamp": 1758196800000, "mood": 4, "energy": 65, "overwhelm": 35, "emotions": ["accomplished", "productive"], "sleepHours": 7.5, "activities": ["self_care"], "week": 1},
  {"id": "1758283200000", "date": "Fri Sep 19 2025", "timestamp": 1758283200000, "mood": 3, "energy": 50, "overwhelm": 50, "emotions": ["tired", "anxious"], "sleepHours": 5.5, "activities": [], "week": 1},
  {"id": "1758369600000", "date": "Sat Sep 20 2025", "timestamp": 1758369600000, "mood": 4, "energy": 75, "overwhelm": 25, "emotions": ["relaxed", "calm"], "sleepHours": 8.5, "activities": ["relaxed_rested", "exercised"], "week": 1},

  {"id": "1758542400000", "date": "Mon Sep 22 2025", "timestamp": 1758542400000, "mood": 3, "energy": 55, "overwhelm": 45, "emotions": ["anxious", "worried"], "sleepHours": 6.0, "activities": [], "week": 2},
  {"id": "1758628800000", "date": "Tue Sep 23 2025", "timestamp": 1758628800000, "mood": 4, "energy": 70, "overwhelm": 30, "emotions": ["motivated", "active"], "sleepHours": 7.5, "activities": ["worked_personal_goal"], "week": 2},
  {"id": "1758715200000", "date": "Wed Sep 24 2025", "timestamp": 1758715200000, "mood": 2, "energy": 40, "overwhelm": 70, "emotions": ["sad", "frustrated"], "sleepHours": 5.0, "activities": [], "week": 2},
  {"id": "1758888000000", "date": "Fri Sep 26 2025", "timestamp": 1758888000000, "mood": 4, "energy": 60, "overwhelm": 40, "emotions": ["average", "calm"], "sleepHours": 6.5, "activities": ["self_care"], "week": 2},
  {"id": "1758974400000", "date": "Sat Sep 27 2025", "timestamp": 1758974400000, "mood": 5, "energy": 80, "overwhelm": 20, "emotions": ["loved", "appreciated"], "sleepHours": 8.0, "activities": ["connected_friends_family"], "week": 2},

  {"id": "1759147200000", "date": "Mon Sep 29 2025", "timestamp": 1759147200000, "mood": 3, "energy": 50, "overwhelm": 50, "emotions": ["average", "tired"], "sleepHours": 6.5, "activities": ["worked_personal_goal"], "week": 3},
  {"id": "1759233600000", "date": "Tue Sep 30 2025", "timestamp": 1759233600000, "mood": 4, "energy": 75, "overwhelm": 25, "emotions": ["accomplished", "grateful"], "sleepHours": 7.0, "activities": ["worked_personal_goal", "self_care"], "week": 3},
  {"id": "1759406400000", "date": "Thu Oct 02 2025", "timestamp": 1759406400000, "mood": 5, "energy": 85, "overwhelm": 15, "emotions": ["joyful", "active"], "sleepHours": 8.0, "activities": ["exercised", "relaxed_rested"], "week": 3},
  {"id": "1759579200000", "date": "Sat Oct 04 2025", "timestamp": 1759579200000, "mood": 4, "energy": 65, "overwhelm": 35, "emotions": ["thankful", "calm"], "sleepHours": 7.5, "activities": ["quality_time_kids"], "week": 3}
]));

localStorage.setItem("emotion-insights-generated", JSON.stringify([1, 2, 3]));

localStorage.setItem("emotion-insights-week-1", JSON.stringify({"analysis":{"weeklyOverview":"This week showed a good balance of positive emotions like excitement and motivation, with moments of joy and peace. While there were a few dips, your overall mood remained relatively stable, which is a great accomplishment as a single parent.","emotionalPatterns":["Your mood generally stayed in the mid-range, indicating a steady emotional state throughout the week.","Energy levels fluctuated but were generally moderate, with a noticeable dip on Friday.","Overwhelm levels remained relatively low, suggesting you managed your responsibilities well."],"keyInsights":["You experienced a good range of positive emotions, including excitement, motivation, joy, and peace.","Despite the demands of single parenting, you maintained a generally stable mood.","There's a clear connection between higher energy and lower overwhelm, and vice versa."],"progressComparison":"No previous week data available.","personalizedTips":["Schedule short, restorative breaks during your day, even just 5-10 minutes, to recharge.","When you feel overwhelmed, try deep breathing exercises or a quick walk to reset.","Celebrate small wins and acknowledge your efforts, as these are significant achievements."],"concernAreas":[],"positiveHighlights":["Experiencing feelings of joy and gratitude on Wednesday.","Ending the week with feelings of relaxation and peace on Saturday."],"nextWeekFocus":"Focus on maintaining your energy levels, perhaps by prioritizing sleep or finding small moments of calm."},"generatedAt":"2025-10-07T04:16:32.370Z"}));

localStorage.setItem("emotion-insights-week-2", JSON.stringify({"analysis":{"weeklyOverview":"This week, you navigated a mix of emotions, experiencing moments of anxiety and overwhelm alongside feelings of hope and love. Despite some challenging days, there's a gentle upward trend in your mood, showing your resilience as a parent.","emotionalPatterns":["Your mood showed improvement over the week, with higher points towards the end.","Energy levels were generally moderate, with a significant boost on Saturday.","Overwhelm fluctuated, with a peak mid-week but generally manageable."],"keyInsights":["Even on tough days, moments of positive emotion like feeling loved and appreciated can significantly lift your spirits.","Your energy and mood seem to be connected; when energy is higher, so is your mood.","Recognizing when overwhelm peaks can help you anticipate and manage those feelings more effectively."],"progressComparison":"Your average mood slightly decreased from 3.83 to 3.6 this week. Energy levels also saw a small dip from 66.7% to 61%. Overwhelm increased from 33.3% to 41%, suggesting a bit more challenge this week compared to last.","personalizedTips":["Schedule small moments of self-care, even just 5 minutes, to recharge when you feel overwhelm rising.","When you feel a surge of positive emotion, take a moment to really soak it in and remember it.","Break down larger tasks into smaller, more manageable steps to reduce feelings of being overwhelmed."],"concernAreas":["The mid-week dip in mood, energy, and spike in overwhelm (Wednesday) is something to keep an eye on."],"positiveHighlights":["Feeling loved and appreciated on Saturday was a wonderful high point, indicating strong connections.","The hopeful and motivated feelings on Tuesday show your capacity for positive outlooks."],"nextWeekFocus":"Focus on building on the positive momentum from Saturday; perhaps aim to create another moment of connection or personal enjoyment mid-week."},"generatedAt":"2025-10-07T04:16:35.642Z"}));

localStorage.setItem("emotion-insights-week-3", JSON.stringify({"analysis":{"weeklyOverview":"This week has been a journey of steady improvement, with your mood and energy levels showing a positive upward trend. You've navigated your days with a sense of accomplishment and calm, which is wonderful!","emotionalPatterns":["Your mood has shown a consistent improvement throughout the week.","Energy levels have been moderate, with a good recovery towards the end of the week.","Overwhelm has remained at a low level, indicating good coping mechanisms."],"keyInsights":["You're successfully managing the daily 'routine' while also finding moments of feeling 'accomplished' and 'proud'.","The dip in energy on Monday was followed by a strong recovery, showing resilience.","Maintaining low overwhelm levels is a great sign of balance, even with parenting demands."],"progressComparison":"This week saw an improvement in your average mood from 3.6/6 to 4/6, and your energy levels increased from 61/100 to 68.75/100. Your overwhelm also decreased from 41/100 to 31.25/100, showing great progress!","personalizedTips":["Schedule small pockets of 'me-time' even for just 10-15 minutes to recharge.","Celebrate small wins, like getting through a busy day or a child's milestone, to boost feelings of accomplishment.","When feeling a dip in energy, try a short walk or some stretching to help re-energize."],"concernAreas":[],"positiveHighlights":["Feeling 'joyful' and 'energized' on Thursday.","Experiencing a sense of being 'calm' and 'satisfied' on Saturday."],"nextWeekFocus":"Continue to acknowledge and build on the feelings of accomplishment and joy you've experienced this week."},"generatedAt":"2025-10-07T04:16:38.509Z"}));

console.log(" Emotion Tracker Test Case 1 injected successfully!");
